# -------------------------------------------------------------------
# General Settings
# -------------------------------------------------------------------
general:
  # Path to the extension directory in Qlik Sense Desktop
  LocalExtensionPath:   "d:\\Documents\\Qlik\\Sense\\Extensions"

  # Name of the Extension as defined in the generator
  ExtensionName:        "Calendar Heatmap"

  # Name of the Extension, safe to be used for file-names
  ExtensionNameSafe:    "CalendarHeatmap"

  # Namespace
  ExtensionNamespace:   "swr-"

  # Description of the Extension as defined in the generator
  ExtensionDescription: "Calendar Heatmap with a diverging color scale. The values are displayed as colored cells per day. Days are arranged into columns by week, then grouped by month and years."

  # Version of the extension, will be re-used in several areas,
  # e.g the generated .zip-file in the 'release' Grunt-task
  Version:              "0.1.0"

# -------------------------------------------------------------------
# Settings for the 'dev' Grunt task
# -------------------------------------------------------------------
dev:
  less: # Documentation: https://github.com/gruntjs/grunt-contrib-less
    lessCompress: false
    lessYuiCompress: false
    lessCleanCss: false
    lessOptimization: 2
  uglify: # Documentation: https://github.com/gruntjs/grunt-contrib-uglify
    mangle: false
    drop_console: false
    beautify: true
    preserveCommments: true
    compress: false

# -------------------------------------------------------------------
# Settings for the 'release' Grunt task
# -------------------------------------------------------------------
release:
  less: # Documentation: https://github.com/gruntjs/grunt-contrib-less
    lessCompress: true
    lessYuiCompress: true
    lessCleanCss: true
    lessOptimization: 2
  uglify: # Documentation: https://github.com/gruntjs/grunt-contrib-uglify
    mangle: true
    drop_console: true
    beautify: false
    preserveCommments: false
    compress: true
